### PR TITLE
Fix Issue 4: Rename Properties -> Interfaces; update refs

### PR DESCRIPTION
**Pull request by shanksauce**
https://www.youtube.com/watch?v=oXyW5w5RRFY&t=2m19s

### CODE REVIEW

**Review by Mateuszpietrusinski — APPROVED** [review]

**Comment by JeffJassky** [comment]
Waiting on this merge. Thanks.

**Comment by c4b4d4** [comment]
Waiting for this merge.

**Comment by thomaslecoeur** [comment]
Waiting for this merge! 👍

**Review by mustit-jschoi — APPROVED** [review]

**Comment by mustit-jschoi** [comment]
Waiting for this merge! Plz....

**Pull request closed without merging**
